### ISSUE TITLE
About the channel weights

### ISSUE THREAD

**Issue by ann1019** [bkong/MCNCC#2]
Hello,
I studied your code recently, 
and found that the channel weights in the code for FID-300 dataset are the same and equal to 1/256.
Besides, I also want to ask the projection matrix of the shoeprint dataset. 
Can i ask the value of learned parameters U,V,W in your research?
Thank you so much.

**Comment by bkong** [comment]
Sorry for the delay. Here's a file with the parameters corresponding to the CCA [mu_c, sigma_c] model for shoeprint matching: [params.zip](https://github.com/bkong/MCNCC/files/2664896/params.zip)

Inside is a MAT file with three variables: **query_T**, **trace_T**, and **w**. query_T and trace_T are the linear transformation matrices for the crime scene prints and laboratory test impressions, respectively, and w is the per-channel importance weights.

**Comment by ann1019** [comment]
Thank you a million!
It's a great work. :D
