### ISSUE TITLE
'batch_size' needs to be fixed into 1(a single image) in generate_db_CNNfeats.m

### ISSUE THREAD

**Issue by seanshnkim** [bkong/MCNCC#3]
Hi, I've been studying your code and I found out that there is a minor bug in setting 'batch_size' in **generate_db_CNNfeats.m** code.
It seems that generate_db_CNNfeats() function takes a single image as input 
but inside the function it handles the input as if it is a mini batch of multiple images.

Here if you look into the code starting from line 11 in **generate_db_CNNfeats.m**, 
'ims' variable is assumed to be 4D array, even though it is a single input image.

```
ims = gather(data{2});
gray = zeros(size(ims, 1), size(ims, 2), 3, size(ims, 4), 'like', ims);
for i=1:size(ims, 4)
  gray(:,:,:, i) = repmat(mean(ims(:,:,:, i), 3), 1, 1, 3);
end
```

'ims' variable is equal to data{2} which is the argument of generate_db_CNNfeats_gpu() function.
And this 'data' comes from **p_im_padded_r** variable (line 114~115 in alignment_search_eval_fid300.m).

```
for offsetx=offsets_x, for offsety=offsets_y
      p_r_feat = generate_db_CNNfeats_gpu(net, ...
        {net.vars(1).name, p_im_padded_r(offsety+1:end, offsetx+1:end, :)});
```
I kept track of 'p_im_padded_r' variable and I found it is padded and rescaled version of FID-300 image (line 67).

```
p_im = imresize(imread(fullfile('datasets', 'FID-300', 'tracks_cropped', sprintf('%05d.jpg', p))), ...
                  imscale);
```

I ran your code in MATLAB and it works fine but when I tried to translate your code in Python,
I see there is no point setting batch_size variable in generate_db_CNNfeats() function
if it only takes a single input image in any case.

Could you please help me to get it work? I'd appreciate your advice on this.

**Comment by bkong** [comment]
What you're missing in your understanding of MATLAB's `size` function is that any dimension beyond what is defined for a variable will return 1. For example, if you define `x = zeros(2, 3, 4);` and run `size(x, 4)`, you'll get 1. So that `generate_db_CNNfeats` and `generate_db_CNNfeats_gpu` were written to support 4D arrays but doesn't have a problem with 3D array. This may not be intuitive coming from Python, but MATLAB supports this behavior.

**Comment by seanshnkim** [comment]
After debugging the code, I figured out that in MATLAB it does work on 3D arrays even if it's treated as 4D array (unlike Python). 

I appreciate that you pointed out the difference between those two, but I still have question on why you intended the function `generate_db_CNNfeats_gpu` to support 4D arrays. 

It is only used in `alignment_search_eval_fid300.m` and `alignment_search_eval_israeli`, and in both cases it takes `p_im_padded_r(offsety+1:end, offsetx+1:end, :)` as an input image. Just a single image, so there is no need to expand it as 4D array.Did you intend to support a mini-batch of multiple images, and later modify the code for some other reason?

**Comment by bkong** [comment]
There was the possibility of needing to support mini batches, so the functions were coded to support it when I initially wrote the functions rather than modifying them later when the need is there.

**Comment by seanshnkim** [comment]
Thanks for replying. At first time I thought that part(preparing mini batches) was omitted by mistake. I should try supporting mini-batches in my re-implementation
